name: "Setup OpenCode auth"
description: "Adds claude code subscription credentials auth.json"

inputs:
  CLAUDE_ACCESS_TOKEN:
    description: "Claude Code Access token"
    required: false
  CLAUDE_REFRESH_TOKEN:
    description: "Claude Code Refresh token"
    required: false
  CLAUDE_EXPIRY:
    description: "Claude Code expiry"
    required: false
  GITHUB_TOKEN:
    description: "GitHub token"
    required: false
  OPENCODE_JSON:
    description: "OpenCode JSON"
    required: false

runs:
  using: "composite"
  steps:
    - name: Write auth.json
      shell: bash
      run: ${{ github.action_path }}/write-claude.sh
      env:
        CLAUDE_ACCESS_TOKEN: ${{ inputs.CLAUDE_ACCESS_TOKEN }}
        CLAUDE_REFRESH_TOKEN: ${{ inputs.CLAUDE_REFRESH_TOKEN }}
        CLAUDE_EXPIRY: ${{ inputs.CLAUDE_EXPIRY }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        OPENCODE_JSON: ${{ inputs.OPENCODE_JSON }}
