/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemosIndexRouteImport } from './routes/demos/index'
import { Route as DemosTimelineRouteImport } from './routes/demos/timeline'
import { Route as DemosPopulationRouteImport } from './routes/demos/population'
import { Route as DemosMutationRouteImport } from './routes/demos/mutation'
import { Route as DemosGeneticRouteImport } from './routes/demos/genetic'
import { Route as DemosEvolutionRouteImport } from './routes/demos/evolution'
import { Route as DemosAssessmentRouteImport } from './routes/demos/assessment'
import { Route as DemosAchievementsRouteImport } from './routes/demos/achievements'
import { Route as DashboardsTeacherRouteImport } from './routes/dashboards/teacher'
import { Route as DashboardsResearchRouteImport } from './routes/dashboards/research'
import { Route as DashboardsLearningRouteImport } from './routes/dashboards/learning'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosIndexRoute = DemosIndexRouteImport.update({
  id: '/demos/',
  path: '/demos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosTimelineRoute = DemosTimelineRouteImport.update({
  id: '/demos/timeline',
  path: '/demos/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosPopulationRoute = DemosPopulationRouteImport.update({
  id: '/demos/population',
  path: '/demos/population',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosMutationRoute = DemosMutationRouteImport.update({
  id: '/demos/mutation',
  path: '/demos/mutation',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosGeneticRoute = DemosGeneticRouteImport.update({
  id: '/demos/genetic',
  path: '/demos/genetic',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosEvolutionRoute = DemosEvolutionRouteImport.update({
  id: '/demos/evolution',
  path: '/demos/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosAssessmentRoute = DemosAssessmentRouteImport.update({
  id: '/demos/assessment',
  path: '/demos/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const DemosAchievementsRoute = DemosAchievementsRouteImport.update({
  id: '/demos/achievements',
  path: '/demos/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsTeacherRoute = DashboardsTeacherRouteImport.update({
  id: '/dashboards/teacher',
  path: '/dashboards/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsResearchRoute = DashboardsResearchRouteImport.update({
  id: '/dashboards/research',
  path: '/dashboards/research',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardsLearningRoute = DashboardsLearningRouteImport.update({
  id: '/dashboards/learning',
  path: '/dashboards/learning',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/tutorial': typeof TutorialRoute
  '/dashboards/learning': typeof DashboardsLearningRoute
  '/dashboards/research': typeof DashboardsResearchRoute
  '/dashboards/teacher': typeof DashboardsTeacherRoute
  '/demos/achievements': typeof DemosAchievementsRoute
  '/demos/assessment': typeof DemosAssessmentRoute
  '/demos/evolution': typeof DemosEvolutionRoute
  '/demos/genetic': typeof DemosGeneticRoute
  '/demos/mutation': typeof DemosMutationRoute
  '/demos/population': typeof DemosPopulationRoute
  '/demos/timeline': typeof DemosTimelineRoute
  '/demos': typeof DemosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/tutorial': typeof TutorialRoute
  '/dashboards/learning': typeof DashboardsLearningRoute
  '/dashboards/research': typeof DashboardsResearchRoute
  '/dashboards/teacher': typeof DashboardsTeacherRoute
  '/demos/achievements': typeof DemosAchievementsRoute
  '/demos/assessment': typeof DemosAssessmentRoute
  '/demos/evolution': typeof DemosEvolutionRoute
  '/demos/genetic': typeof DemosGeneticRoute
  '/demos/mutation': typeof DemosMutationRoute
  '/demos/population': typeof DemosPopulationRoute
  '/demos/timeline': typeof DemosTimelineRoute
  '/demos': typeof DemosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery': typeof GalleryRoute
  '/tutorial': typeof TutorialRoute
  '/dashboards/learning': typeof DashboardsLearningRoute
  '/dashboards/research': typeof DashboardsResearchRoute
  '/dashboards/teacher': typeof DashboardsTeacherRoute
  '/demos/achievements': typeof DemosAchievementsRoute
  '/demos/assessment': typeof DemosAssessmentRoute
  '/demos/evolution': typeof DemosEvolutionRoute
  '/demos/genetic': typeof DemosGeneticRoute
  '/demos/mutation': typeof DemosMutationRoute
  '/demos/population': typeof DemosPopulationRoute
  '/demos/timeline': typeof DemosTimelineRoute
  '/demos/': typeof DemosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery'
    | '/tutorial'
    | '/dashboards/learning'
    | '/dashboards/research'
    | '/dashboards/teacher'
    | '/demos/achievements'
    | '/demos/assessment'
    | '/demos/evolution'
    | '/demos/genetic'
    | '/demos/mutation'
    | '/demos/population'
    | '/demos/timeline'
    | '/demos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery'
    | '/tutorial'
    | '/dashboards/learning'
    | '/dashboards/research'
    | '/dashboards/teacher'
    | '/demos/achievements'
    | '/demos/assessment'
    | '/demos/evolution'
    | '/demos/genetic'
    | '/demos/mutation'
    | '/demos/population'
    | '/demos/timeline'
    | '/demos'
  id:
    | '__root__'
    | '/'
    | '/gallery'
    | '/tutorial'
    | '/dashboards/learning'
    | '/dashboards/research'
    | '/dashboards/teacher'
    | '/demos/achievements'
    | '/demos/assessment'
    | '/demos/evolution'
    | '/demos/genetic'
    | '/demos/mutation'
    | '/demos/population'
    | '/demos/timeline'
    | '/demos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryRoute: typeof GalleryRoute
  TutorialRoute: typeof TutorialRoute
  DashboardsLearningRoute: typeof DashboardsLearningRoute
  DashboardsResearchRoute: typeof DashboardsResearchRoute
  DashboardsTeacherRoute: typeof DashboardsTeacherRoute
  DemosAchievementsRoute: typeof DemosAchievementsRoute
  DemosAssessmentRoute: typeof DemosAssessmentRoute
  DemosEvolutionRoute: typeof DemosEvolutionRoute
  DemosGeneticRoute: typeof DemosGeneticRoute
  DemosMutationRoute: typeof DemosMutationRoute
  DemosPopulationRoute: typeof DemosPopulationRoute
  DemosTimelineRoute: typeof DemosTimelineRoute
  DemosIndexRoute: typeof DemosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/': {
      id: '/demos/'
      path: '/demos'
      fullPath: '/demos'
      preLoaderRoute: typeof DemosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/timeline': {
      id: '/demos/timeline'
      path: '/demos/timeline'
      fullPath: '/demos/timeline'
      preLoaderRoute: typeof DemosTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/population': {
      id: '/demos/population'
      path: '/demos/population'
      fullPath: '/demos/population'
      preLoaderRoute: typeof DemosPopulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/mutation': {
      id: '/demos/mutation'
      path: '/demos/mutation'
      fullPath: '/demos/mutation'
      preLoaderRoute: typeof DemosMutationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/genetic': {
      id: '/demos/genetic'
      path: '/demos/genetic'
      fullPath: '/demos/genetic'
      preLoaderRoute: typeof DemosGeneticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/evolution': {
      id: '/demos/evolution'
      path: '/demos/evolution'
      fullPath: '/demos/evolution'
      preLoaderRoute: typeof DemosEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/assessment': {
      id: '/demos/assessment'
      path: '/demos/assessment'
      fullPath: '/demos/assessment'
      preLoaderRoute: typeof DemosAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demos/achievements': {
      id: '/demos/achievements'
      path: '/demos/achievements'
      fullPath: '/demos/achievements'
      preLoaderRoute: typeof DemosAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/teacher': {
      id: '/dashboards/teacher'
      path: '/dashboards/teacher'
      fullPath: '/dashboards/teacher'
      preLoaderRoute: typeof DashboardsTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/research': {
      id: '/dashboards/research'
      path: '/dashboards/research'
      fullPath: '/dashboards/research'
      preLoaderRoute: typeof DashboardsResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboards/learning': {
      id: '/dashboards/learning'
      path: '/dashboards/learning'
      fullPath: '/dashboards/learning'
      preLoaderRoute: typeof DashboardsLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryRoute: GalleryRoute,
  TutorialRoute: TutorialRoute,
  DashboardsLearningRoute: DashboardsLearningRoute,
  DashboardsResearchRoute: DashboardsResearchRoute,
  DashboardsTeacherRoute: DashboardsTeacherRoute,
  DemosAchievementsRoute: DemosAchievementsRoute,
  DemosAssessmentRoute: DemosAssessmentRoute,
  DemosEvolutionRoute: DemosEvolutionRoute,
  DemosGeneticRoute: DemosGeneticRoute,
  DemosMutationRoute: DemosMutationRoute,
  DemosPopulationRoute: DemosPopulationRoute,
  DemosTimelineRoute: DemosTimelineRoute,
  DemosIndexRoute: DemosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
